apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meshcloud-storage
  labels:
    app: meshcloud
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meshcloud-database
  labels:
    app: meshcloud
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard